### ISSUE TITLE
Граф управления потока

### ISSUE THREAD

**Issue by voloshinbogdan** [wisestump/OptimizingCompiler#2]
Путь для реализации [`src\DataFlowAnalysis\IntermediateRepresentation\ControlFlowGraph`](https://github.com/wisestump/OptimizingCompiler/tree/master/src/DataFlowAnalysis/IntermediateRepresentation/ControlFlowGraph)

**Comment by kolsolv** [comment]
Тесты для графа есть в MeetOverPathsTests
