### ISSUE TITLE
Привести 3 примера программ, дающих неприводимые графы

### ISSUE THREAD

**Issue by wisestump** [wisestump/OptimizingCompiler#22]
Для таких программ найти отступающие ребра, не являющиеся обратными

**Comment by ammsaid** [comment]
В эту же задачу входило задание: "Найти отступающие ребра, не являющиеся обратными". Вместо этого мы реализовали поиск обратных ребер, а поиск отступающих и не обратных, опирающийся на этот алгоритм, ложится на задачу определения неприводимости графа. #20
