### ISSUE TITLE
Получение 3х адресного кода по CFG

### ISSUE THREAD

**Issue by voloshinbogdan** [wisestump/OptimizingCompiler#3]
Путь для реализации [`src\DataFlowAnalysis\IntermediateRepresentation\ControlFlowGraph`](https://github.com/wisestump/OptimizingCompiler/tree/master/src/DataFlowAnalysis/IntermediateRepresentation/ControlFlowGraph)

**Comment by sigiward** [comment]
коммит: https://github.com/wisestump/OptimizingCompiler/commit/72c8860f521db2ecd474d5ac432111c2e8c33b75

Реализовано в виде метода CFG.transformToThreeAddressCode()
