### ISSUE TITLE
Множества gen B и kill B(на основе передаточной функции по явным формулам)

### ISSUE THREAD

**Issue by voloshinbogdan** [wisestump/OptimizingCompiler#4]
Путь для реализации [`src\DataFlowAnalysis\IntermediateRepresentation\CFGComponents`](https://github.com/wisestump/OptimizingCompiler/tree/master/src/DataFlowAnalysis/IntermediateRepresentation/CFGComponents)

**Comment by Dysthymiac** [comment]
Поглощено тестами для итерационного алгоритма на основе передаточной функции по явным формулам для достигающих определений
