### ISSUE TITLE
Вычисление передаточной функции, как композиции передаточных функций для одной команды

### ISSUE THREAD

**Issue by voloshinbogdan** [wisestump/OptimizingCompiler#6]
Путь для реализации [`src\DataFlowAnalysis\IntermediateRepresentation\CFGComponents`](https://github.com/wisestump/OptimizingCompiler/tree/master/src/DataFlowAnalysis/IntermediateRepresentation/CFGComponents)

**Comment by a6461** [comment]
Поглощено тестами для итерационного алгоритма на основе передаточной функции по явным формулам для достигающих определений
